In [4]:
import pandas as pd


df = pd.read_csv('data/tourism_with_id.csv')



df = df.drop(['Unnamed: 11', 'Unnamed: 12', 'Lat', 'Long', 'Coordinate', 'Time_Minutes'], axis=1)


"""
I want to normalize df['Rating'] data so that the value is between 0 until 5 because the rating value is between 0 until 5. 

I want to change the label become like this:

4.0 , 4.1 ==> 1,
4.2, 4.3 ==> 2,
4.4, 4.5 ==> 3,
4.6, 4.7 ==> 4,
4.8, 4.9, 5.0 ==> 5
"""

# change the label

df['Rating'] = df['Rating'].replace([4.0, 4.1], 0)
df['Rating'] = df['Rating'].replace([4.2, 4.3], 1)
df['Rating'] = df['Rating'].replace([4.4, 4.5], 2)
df['Rating'] = df['Rating'].replace([4.6, 4.7], 3)
df['Rating'] = df['Rating'].replace([4.8, 4.9, 5.0], 4)

# convert data to int

df["Rating"] = df["Rating"].astype(int)

# select only yogyakarta city

df = df[df['City'] == 'Yogyakarta']


# save the dataframe to csv file

df.to_csv('data/new_data.csv', index=False)


df.head(10)

,Place_Id,Place_Name,Description,Category,City,Price,Rating
84,85,Taman Pintar Yogyakarta,Taman Pintar Yogyakarta (bahasa Jawa: Hanacara...,Taman Hiburan,Yogyakarta,6000,2
85,86,Keraton Yogyakarta,Keraton Ngayogyakarta Hadiningrat atau Keraton...,Budaya,Yogyakarta,15000,3
86,87,Sindu Kusuma Edupark (SKE),Sindu Kusuma Edupark (SKE) merupakan sebuah de...,Taman Hiburan,Yogyakarta,20000,1
87,88,Museum Benteng Vredeburg Yogyakarta,Museum Benteng Vredeburg (bahasa Jawa: ꦩꦸꦱꦶꦪꦸꦩ...,Budaya,Yogyakarta,3000,3
88,89,De Mata Museum Jogja,Museum De Mata merupakan salah satu museum yan...,Budaya,Yogyakarta,50000,2
89,90,Kampung Wisata Taman Sari,Taman Sari Yogyakarta atau Taman Sari Keraton ...,Taman Hiburan,Yogyakarta,5000,3
90,91,Situs Warungboto,Situs Warungboto atau Pesanggrahan Rejawinangu...,Taman Hiburan,Yogyakarta,0,2
91,92,Nol Kilometer Jl.Malioboro,"Walaupun hanyalah sebuah persimpangan, namun p...",Taman Hiburan,Yogyakarta,0,3
92,93,Gembira Loka Zoo,Kebun Binatang Gembira Loka biasa disebut Gemb...,Cagar Alam,Yogyakarta,60000,2
93,94,Sumur Gumuling,Sumur Gumuling adalah salah satu tempat untuk ...,Taman Hiburan,Yogyakarta,7000,2

In [1]:
import tensorflow as tf
import numpy as np








category_test = 4

price_test = 2

input_data = np.array([[category_test, price_test]], dtype=np.float32)

interpreter = tf.lite.Interpreter(model_path="model.tflite")

interpreter.allocate_tensors()

input_details = interpreter.get_input_details()

output_details = interpreter.get_output_details()

interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])

print(output_data)

print(np.argmax(output_data))

# Menampilkan tempat wisata sesuai dengan rating 
for i in range(len(df)):
    if df['Rating'][i] == np.argmax(output_data):
        print(df['Place_Name'][i])

2023-06-04 13:48:17.798719: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-06-04 13:48:17.798771: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

[[1.9528838e-06 7.8526735e-01 2.1461055e-01 1.2020199e-04 1.4574134e-20
  7.1943634e-26]]
1
Pulau Pramuka
Jembatan Kota Intan
Pecinan Glodok
Wisata Alam Mangrove Angke
Taman Agrowisata Cilangkap
Margasatwa Muara Angke
SnowBay Waterpark
Hutan Kota Srengseng
Alive Museum Ancol
Sindu Kusuma Edupark (SKE)
Taman Pelangi Yogyakarta
The Lost World Castle
Monumen Sanapati
The World Landmarks - Merapi Park Yogyakarta
Kampung Wisata Rejowinangun
Pantai Goa Cemara
Blue Lagoon Jogja
Watu Lumbung
Goa Rancang Kencono
Green Village Gedangsari
Puncak Segoro
Pantai Depok Jogja
Galaxy Waterpark Jogja
Pantai Congot
Dago Dreampark
Panghegar Waterboom Bandung
Teras Cikapundung BBWS
Monumen Bandung Lautan Api
Ciwangun Indah Camp Official
Taman Vanda
Taman Budaya Jawa Barat
Curug Bugbrug
Peta Park
Pasar Baru
Taman Film
Sendang Geulis Kahuripan
Pemandian Air Panas Ciater
The Lodge Maribaya
Tafso Barn
Curug Luhur Waterfall
Kawah Rengganis Cibuni
Bukit Jamur
Happyfarm Ciwidey
Kampung Pelangi
Hutan Wisata Tinjomoyo Semarang
Wisata Mangrove Tapak
Taman Bunga Celosia
Water Blaster Bukit Candi Golf
Waduk Jatibarang
Wisata Lereng Kelir
Benteng Pendem
Wisata Eling Bening
Jembatan Biru Ambarawa
Goa Rong
Kampoeng Kopi Banaran
Obyek Wisata Goa Kreo
Brown Canyon
Ekowisata Mangrove Wonorejo
Hutan Bambu Keputih
Taman Keputran
Taman Barunawati
Kenjeran Park
Kebun Binatang Surabaya
Ciputra Waterpark
Pantai Ria Kenjeran
Patung Buddha Empat Rupa
Taman Hiburan Rakyat